// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8isyPP32vRgMTtTc66OGFWf9mSayuGWI',
    appId: '1:78116113745:web:ac096cbeb9283f486e5770',
    messagingSenderId: '78116113745',
    projectId: 'rosheta-b6472',
    authDomain: 'rosheta-b6472.firebaseapp.com',
    storageBucket: 'rosheta-b6472.appspot.com',
    measurementId: 'G-1XRWZPNC9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1xegOem95bh6CWEkRRhFVspsJzm6TmCU',
    appId: '1:78116113745:android:eb3e1256f9252bb06e5770',
    messagingSenderId: '78116113745',
    projectId: 'rosheta-b6472',
    storageBucket: 'rosheta-b6472.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApUVPFRDJY0AlA2mViNUOOxZdIFmwGH7o',
    appId: '1:78116113745:ios:4ed88887251678296e5770',
    messagingSenderId: '78116113745',
    projectId: 'rosheta-b6472',
    storageBucket: 'rosheta-b6472.appspot.com',
    iosBundleId: 'com.example.roshetaUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApUVPFRDJY0AlA2mViNUOOxZdIFmwGH7o',
    appId: '1:78116113745:ios:4ed88887251678296e5770',
    messagingSenderId: '78116113745',
    projectId: 'rosheta-b6472',
    storageBucket: 'rosheta-b6472.appspot.com',
    iosBundleId: 'com.example.roshetaUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8isyPP32vRgMTtTc66OGFWf9mSayuGWI',
    appId: '1:78116113745:web:10760f7dd25be5856e5770',
    messagingSenderId: '78116113745',
    projectId: 'rosheta-b6472',
    authDomain: 'rosheta-b6472.firebaseapp.com',
    storageBucket: 'rosheta-b6472.appspot.com',
    measurementId: 'G-JFKH4KN0BD',
  );
}
